POST http://localhost:3000/campaigns

{
  "name": "Test 2",
  "content": "This t",
  "emails": ["marlom1012@gmail.com", "xxx@gmail.com"]
} 

###

GET  http://localhost:3000/campaigns

###
GET http://localhost:3000/campaigns/cu0udl5qr20uf91gv69g

### 
PATCH http://localhost:3000/campaigns/cancel/cu0udl5qr20uf91gv69g

