@URL= http://localhost:3000
@token = Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJqcDQzQnI2X284QlljSjhnVXQ2RmhmajZmVERnWE51NVpVdVE3TlliVDlZIn0.eyJleHAiOjE3MzY2NTAwMDQsImlhdCI6MTczNjY0OTcwNCwianRpIjoiYzhhMjcyOWQtNDEwOS00MDFiLWExYjctZGYxMTQ5MDI1NWUzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlckdPIiwiYXVkIjoiZW1haWxuIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZW1haWxuIiwic2lkIjoiNjNlMWZlNWQtMmI1Yi00NTZkLWFhZDYtOWM1MGUxNDBjODFhIiwic2NvcGUiOiIifQ.ofBXXOCs57o-yg_k-y9TFOjBCRixhzd7KXmJxZ2N6XnKJjuAjcSDskMSL2IvkUuoDwcP6nh8yJdCRSr1eSi_QhvgFzJlLWR5sjywrOWv6s0fLdDdJguXBs5mYUnjhnuntRhWkA6UoZxUBWk_mPz9ryuuwxbyk64lT7ZDX0NAd4SOtDGHEbPObxtwEVRjhkAR47x7hBxM86WIJoK0zPpLTYAq995HXwQuQjjWkb34--7H7aK2x-40A2aTkt6qMsQibR0VZZBQPwHjwxh1D1brJtlPhd90f4QwQrlOGT7GPeD-iVCKBrkJ0jfSGJH9E5PZDRZsLX6DQQGKOz7ngWkgAg

###
GET  {{URL}}/ping

###
# @name id
POST {{URL}}/campaigns
Authorization: {{token}}

{
  "name": "Test 6",
  "content": "This t",
  "emails": ["marlom1012@gmail.com", "xxx@gmail.com"]
} 

###

GET  {{URL}}/campaigns
Authorization: {{token}}

###
GET {{URL}}/campaigns/cu0udl5qruf91gv69g
Authorization: {{token}}


### 
PATCH {{URL}}/campaigns/cancel/cu0udl5qruf91gv69g
Authorization: {{token}}


###
DELETE {{URL}}/campaigns/cu1dpl5qr20mpm6i7s6g
Authorization: {{token}}
