@URL= http://localhost:3000
@token = Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJqcDQzQnI2X284QlljSjhnVXQ2RmhmajZmVERnWE51NVpVdVE3TlliVDlZIn0.eyJleHAiOjE3MzY2NTMxNDAsImlhdCI6MTczNjY1Mjg0MCwianRpIjoiOGNjYjMyM2EtZTcwYi00Y2Q2LTljNzMtMWNkYTNhNmE1YjA0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlckdPIiwiYXVkIjoiZW1haWxuIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZW1haWxuIiwic2lkIjoiODhmYjY3YzYtZTg5Yi00MTE5LWIyYjctNTc1ZWU5MmJkYmZmIiwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoibWFybG9tIHNvdXphIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibWFybG9tIiwiZ2l2ZW5fbmFtZSI6Im1hcmxvbSIsImZhbWlseV9uYW1lIjoic291emEiLCJlbWFpbCI6Im1hcmxvbTEwMTJAZ21haWwuY29tIn0.T5J5fAu9Zl6w0aTQighNWtEhM62ps4yZdreWfOGN3bEze38_qYcPJ1ZXIolp1fHtN9oq1MGVppEk4VvUa3yQQfa76y4o9FdI2hpN4y5Xe8AUTyUsfeqNoVdyr2CYz_vFHcqOVR1_ElrMRs61itiY05witi1R_o0w2dVOLNGJX5YFCcPUDppNRtbZZSCgYUA-BDccwqiYR4HfPSNUgChC2KV1nmdrIDE086jkXopyX2MDFZsEIKsCb5IStrlXTaBR5xED4RHvcUKAIEgC1AX_8d23nTU4-ysVzhq4zvuf_hhjw6hPLB-R9AwfxsnC-QhMk8z3kXgED5DOLes4MZSl1g

###
GET  {{URL}}/ping

###
# @name id
POST {{URL}}/campaigns
Authorization: {{token}}

{
  "name": "Test 6",
  "content": "This t",
  "emails": ["marlom1012@gmail.com", "xxx@gmail.com"]
} 

###

GET  {{URL}}/campaigns
Authorization: {{token}}

###
GET {{URL}}/campaigns/cu0udl5qruf91gv69g
Authorization: {{token}}


### 
PATCH {{URL}}/campaigns/cancel/cu0udl5qruf91gv69g
Authorization: {{token}}


###
DELETE {{URL}}/campaigns/cu1dpl5qr20mpm6i7s6g
Authorization: {{token}}
